[[headers]]
  for = "/*.gz"
  [headers.values]
    Content-Encoding = "gzip"

# Specific overrides for Unity-specific extensions
[[headers]]
  for = "/*.wasm.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.js.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.data.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.unityweb"
  [headers.values]
    Content-Encoding = "gzip"